# Build with Dockerfile (uses npm install --legacy-peer-deps) and push to Artifact Registry.
# In your Cloud Build trigger, set "Cloud Build configuration file" to: cloudbuild.yaml
#
# IMPORTANT: Uses existing Artifact Registry repository: cloud-run-source-deploy
# This repository should already exist (created by Cloud Run source deployments)
#
# Using existing Artifact Registry repository: cloud-run-source-deploy
# Built-in variables: $PROJECT_ID, $SHORT_SHA are auto-provided by Cloud Build

steps:
  # Build with local tag first to avoid registry authentication during build
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'impactflow-os:${SHORT_SHA}'
      - '.'

  # Tag with Artifact Registry path
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'tag'
      - 'impactflow-os:${SHORT_SHA}'
      - 'us-west1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/martijn-s-projects-impactflow-os/impactflow-os:${SHORT_SHA}'

  # Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-west1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/martijn-s-projects-impactflow-os/impactflow-os:${SHORT_SHA}'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'impactflow-os'
      - '--image'
      - 'us-west1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/martijn-s-projects-impactflow-os/impactflow-os:${SHORT_SHA}'
      - '--region'
      - 'us-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'us-west1-docker.pkg.dev/${PROJECT_ID}/cloud-run-source-deploy/martijn-s-projects-impactflow-os/impactflow-os:${SHORT_SHA}'

# Required when the trigger uses a custom service account (satisfies option c).
# IMPORTANT: The trigger MUST be set to "Cloud Build configuration file" (not "Dockerfile")
# and the path must be: cloudbuild.yaml (since this file is in the repo root)
options:
  logging: 'CLOUD_LOGGING_ONLY'