# Build with Dockerfile (uses npm install --legacy-peer-deps) and push to Artifact Registry.
# Use this file in your Cloud Run trigger: set "Cloud Build configuration file" to
# impactflow-os/cloudbuild.yaml (if repo root is parent) or cloudbuild.yaml (if repo root is here).
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/impactflow-os:${SHORT_SHA}'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/impactflow-os:${SHORT_SHA}'

images:
  - '${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/impactflow-os:${SHORT_SHA}'

# Required when the trigger uses a custom service account (satisfies logging requirement)
options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET